name: React-App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t nitesh/react-app -f ./Dockerfile.dev ./
      - run: docker run -e CI=true nitesh/react-app npm test
